

services:

  # QuizService
  quizservice:
    build: ../quizservice
    ports:
      - '8081:8081'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:~/learningapp
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
      - AMQP_EXCHANGE_NAME=learningAppExchange
      - AMQP_QUEUE_COMPLETE_NAME=quiz.complete
    volumes:
      - quizservice-data:/data
    depends_on:
      - rabbitmq-dev
      - consul-dev
    networks:
      - my_quiz_app_network

  # ScoreService
  scoreservice:
    build: ../scoreservice
    ports:
      - '8082:8082'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:~/learningapp
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
      - AMQP_EXCHANGE_NAME=learningAppExchange
      - AMQP_QUEUE_COMPLETE_NAME=quiz.complete
    volumes:
      - quizservice-data:/data
    depends_on:
      - rabbitmq-dev
      - consul-dev
    networks:
      - my_quiz_app_network

  # Gateway
  gateway:
    build: ../gateway
    ports:
      - '8000:8000'
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
    depends_on:
      - rabbitmq-dev
      - consul-dev
    networks:
      - my_quiz_app_network

  # LoginService
  loginservice:
    build: ../loginservice
    ports:
      - '8084:8084'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:~/learningapp
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
      - AMQP_EXCHANGE_NAME=learningAppExchange
      - AMQP_QUEUE_COMPLETE_NAME=user.queue
    volumes:
      - quizservice-data:/data
    depends_on:
      - rabbitmq-dev
      - consul-dev
    networks:
      - my_quiz_app_network

  # FlashcardService
  flashcardservice:
    build: ../flashcardservice
    ports:
      - '8087:8087'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:~/learningapp
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONSUL_HOST=consul
    volumes:
      - quizservice-data:/data
    depends_on:
      - quizservice
      - consul-dev
    networks:
      - my_quiz_app_network



  # RabbitMQ
  rabbitmq-dev:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - my_quiz_app_network

  # Consul
  consul-dev:
    image: hashicorp/consul:1.19.2
    container_name: consul
    ports:
      - '8500:8500'
    command: 'agent -dev -node=quiz-node -client=0.0.0.0 -log-level=INFO'
    networks:
      - my_quiz_app_network

volumes:
  quizservice-data:
    driver: local

networks:
  my_quiz_app_network:
    driver: bridge

