spring:
  application:
    name: scoreservice
  datasource:
    url: jdbc:h2:mem:scoreservice
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: '*'
