FROM openjdk:21
COPY ./target/flashcardservice-0.0.1-SNAPSHOT.jar /usr/src/flashcardservice/
WORKDIR /usr/src/flashcardservice/
EXPOSE 8087
CMD ["java", "-jar", "flashcardservice-0.0.1-SNAPSHOT.jar"]
